###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.1
      container_name: thelia_app-mariadb
      working_dir: /application
      volumes:
        - .:/application
        - .docker/mysql-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=thelia_app
        - MYSQL_USER=thelia_app
        - MYSQL_PASSWORD=thelia_app
      ports:
        - "8036:3306"
        
    webserver:
      image: nginx:alpine
      container_name: thelia_app-webserver
      working_dir: /application
      volumes:
          - .:/application:cached
          - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: .docker/php-fpm
      container_name: thelia_app-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - .docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - .docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
      environment:
        XDEBUG_CONFIG: "remote_host=docker.for.mac.host.internal"
        PHP_IDE_CONFIG: "serverName=thelia_app"

